# Generated by Django 5.0.6 on 2024-07-01 06:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(max_length=50)),
                ('otros_autores', models.CharField(blank=True, max_length=100, null=True)),
                ('resena', models.TextField(blank=True, null=True)),
                ('editorial', models.CharField(max_length=40)),
                ('anio_edicion', models.IntegerField()),
                ('pais_edicion', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('N', 'Novela'), ('P', 'Poesía'), ('CU', 'Cuentos'), ('D', 'Dramaturgia'), ('E', 'Ensayo'), ('F', 'Filosofía'), ('H', 'Historia'), ('A', 'Arte'), ('CA', 'Cartas')], max_length=2)),
                ('estado_libro', models.CharField(choices=[('D', 'Disponible'), ('R', 'Reservado'), ('PR', 'Prestado'), ('ER', 'En reparación'), ('PE', 'Perdido')], default='D', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numero_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_libros', models.IntegerField(default=0)),
                ('fec_reserva', models.DateField(auto_now_add=True)),
                ('fec_compromiso', models.DateField(blank=True, null=True)),
                ('fec_listo_ret', models.DateField(blank=True, null=True)),
                ('fec_max_ret', models.DateField(blank=True, null=True)),
                ('fec_retiro', models.DateField(blank=True, null=True)),
                ('fec_dev_prog', models.DateField(blank=True, null=True)),
                ('fec_dev_real', models.DateField(blank=True, null=True)),
                ('fec_cancelacion', models.DateField(blank=True, null=True)),
                ('ult_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_reserva', models.CharField(choices=[('R', 'Reservada'), ('LR', 'Lista para retiro'), ('CO', 'Retirada'), ('D', 'Devuelta'), ('CA', 'Cancelada')], default='R', max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id_detalle_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'libro')},
            },
        ),
    ]
