# Generated by Django 5.0.6 on 2024-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fec_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Reservada'), ('LR', 'Lista para retiro'), ('CO', 'Retirada'), ('D', 'Devuelta'), ('CA', 'Cancelada')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fec_reserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
