# Generated by Django 5.0.6 on 2024-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_reserva_fec_creacion_alter_reserva_estado_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fec_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
