# Generated by Django 5.0.6 on 2024-07-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_reserva_fec_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_reserva', to='biblioteca.reserva'),
        ),
    ]
